### PR TITLE
Class name and method has been updated

### PR DESCRIPTION
**Pull request by staaankey**
- Enum HabitShopingListitemStatus renamed to **HabitShopingListitemStatus**

- Method updateUserShopingListItemStatus renamed to **updateUserShoppingListItemStatus**

### CODE REVIEW

**Review by lagysha — APPROVED** [review]
Nice

**Comment by DenysLiubchenko** [comment]
I wrote test for ShoppingListItemController, so when merging we need to change name for updateUserShoppingListItemStatus method.

**Review by DenysLiubchenko — APPROVED** [review]

**Comment by staaankey** [comment]
> I wrote test for ShoppingListItemController, so when merging we need to change name for updateUserShoppingListItemStatus method.

Okay. I will keep in eye this moment. So when the time comes to merge i will mention you or directly write in pm

**Review by urio999 — APPROVED** [review]

**Review by OleksandrKobetsDev — APPROVED** [review]
well done

**Pull request closed without merging**
